### ISSUE TITLE
persistent data storage with shiny

### ISSUE THREAD

**Issue by jeyapramila** [daattali/shiny-server#7]
it is not working, what to do???

**Comment by jeyapramila** [comment]
![screenshot 2018-01-25 12 19 16](https://user-images.githubusercontent.com/35023211/35374694-0afd9e76-01ca-11e8-9272-c42afbe3cbd7.png)

**Comment by daattali** [comment]
This is not supposed to work out of the box. Please read the associated blog post: https://deanattali.com/blog/shiny-persistent-data-storage/ it will explain how to get it to work. My code makes use of some private variables that I haven't made public and that's why copying my exact code will not work.

**Comment by jeyapramila** [comment]
But please help me to run

**Comment by edeo** [comment]
jeyapramilia, can you show us the errors you are getting?

**Comment by daattali** [comment]
Unfortunately it's not a quick easy fix to get the app to work, you really do need to read and understand the background information. In the code you will see many references to `options()`, these are variables that you must set with appropriate values

**Comment by jeyapramila** [comment]
Ok,  thanks
